import { LayoutPlugin, LayoutPluginContext, LayoutPluginResult, Placeholder, RegisteredLayoutPlugin } from '../types';

const registry: RegisteredLayoutPlugin[] = [];

export function registerLayoutPlugin(plugin: LayoutPlugin) {
  if (!registry.find(p => p.id === plugin.id)) registry.push({ ...plugin, enabled: true });
}

export function listLayoutPlugins(): RegisteredLayoutPlugin[] { return registry.slice(); }
export function setLayoutPluginEnabled(id: string, enabled: boolean) {
  const p = registry.find(r => r.id === id);
  if (p) p.enabled = enabled;
}
export function getLayoutPlugin(id: string): RegisteredLayoutPlugin | undefined { return registry.find(r => r.id === id); }
export function listEnabledLayoutPlugins(): RegisteredLayoutPlugin[] { return registry.filter(p => p.enabled); }

// Example plugin: dense collage 4x2
registerLayoutPlugin({
  id: 'dense-4x2',
  label: 'Dense 4x2 Collage',
  version: '1.0.0',
  author: 'system',
  description: 'Generates 8 evenly spaced slots with small margins.',
  generate: (ctx: LayoutPluginContext): LayoutPluginResult => {
    const margin = 0.04;
    const gap = 0.02;
    const rows = 2; const cols = 4;
    const availW = 1 - margin * 2 - gap * (cols - 1);
    const availH = 1 - margin * 2 - gap * (rows - 1);
    const w = availW / cols;
    const h = availH / rows;
    const placeholders: Placeholder[] = [];
    let idCounter = Date.now();
    for (let r = 0; r < rows; r++) {
      for (let c = 0; c < cols; c++) {
        placeholders.push({ id: idCounter++, x: margin + c * (w + gap), y: margin + r * (h + gap), width: w, height: h, aspectRatio: null, fit: 'cover' });
      }
    }
    return { placeholders, notes: ['Generated by dense-4x2 plugin'] };
  },
  validate: (placeholders: Placeholder[]): { message: string; severity: 'info' | 'warning' | 'error'; }[] => {
    const issues: { message: string; severity: 'info' | 'warning' | 'error'; }[] = [];
    if (placeholders.length !== 8) issues.push({ message: 'Expected 8 placeholders', severity: 'warning' });
    return issues;
  }
});
